version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/CMS/build
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file