version: 0.2

phases:
  pre_build:
    commands:
      - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      - sudo apt-get install -y nodejs
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm install
      - cd $CODEBUILD_SRC_DIR; npm run build
artifacts:
  files:
    - $CODEBUILD_SRC_DIR/build/**/*
    - $CODEBUILD_SRC_DIR/scripts/**/*
    - $CODEBUILD_SRC_DIR/appspec.yml
  discard-paths: yes